### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NightRaidGamer** [Proton-git/BruteRatel-1.2.2-Scandinavian-Defense#3]
hello could you tell me if there is a way to run brute ratel on windows?

**Comment by Proton-git** [comment]
Hello, yeah sure Cheytan Nayak just drop an updated version who run perfectly on windows

source : https://twitter.com/NinjaParanoid/status/1662124802327576576

**Comment by NightRaidGamer** [comment]
> Hello, yeah sure Cheytan Nayak just drop an updated version who run perfectly on windows
> 
> source : https://twitter.com/NinjaParanoid/status/1662124802327576576

thanks
